const CONFIG_VALIDATION_REGEX = /^([CAR]{1}[10]{0,1}[-]{0,1})+$/;

const CAESAR_CIPHER_KEY = 'C';
const ATBASH_CIPHER_KEY = 'A';
const ROT8_CIPHER_KEY = 'R';

const CIPHER_MARKS = [CAESAR_CIPHER_KEY, ATBASH_CIPHER_KEY, ROT8_CIPHER_KEY];
const CODING_FLAGS = ['1', '0'];

const CONFIG_KEY_NAME = '--config';
const CONFIG_KEY_ALIAS = '-c';
const INPUT_KEY_NAME = '--input';
const INPUT_KEY_ALIAS = '-i';
const OUTPUT_KEY_NAME = '--output';
const OUTPUT_KEY_ALIAS = '-o';

const CLI_OPTIONS_KEYS = {
    config: {
        name: '--config',
        alias: '-c',
    },
    input: {
        name: '--input',
        alias: '-i',
    },
    output: {
        name: '--output',
        alias: '-o',
    },
};

const CONFIG_COMMANDS = [CONFIG_KEY_ALIAS, CONFIG_KEY_NAME];
const INPUT_COMMANDS = [INPUT_KEY_ALIAS, INPUT_KEY_NAME];
const OUTPUT_COMMANDS = [OUTPUT_KEY_ALIAS, OUTPUT_KEY_NAME];

const CLI_OPTIONS_ALIAS_TO_NAME_MAP = {
    [CONFIG_KEY_ALIAS]: CONFIG_KEY_NAME,
    [INPUT_KEY_ALIAS]: INPUT_KEY_NAME,
    [OUTPUT_KEY_ALIAS]: OUTPUT_KEY_NAME,
};

const CLI_OPTIONS_NAME_TO_ALIAS_MAP = {
    [CONFIG_KEY_NAME]: CONFIG_KEY_ALIAS,
    [INPUT_KEY_NAME]: INPUT_KEY_ALIAS,
    [OUTPUT_KEY_NAME]: OUTPUT_KEY_ALIAS,
};

module.exports = {
    CONFIG_VALIDATION_REGEX,
    CAESAR_CIPHER_KEY,
    ATBASH_CIPHER_KEY,
    ROT8_CIPHER_KEY,
    CIPHER_MARKS,
    CODING_FLAGS,
    CLI_OPTIONS_KEYS,
    CONFIG_COMMANDS,
    INPUT_COMMANDS,
    OUTPUT_COMMANDS,
    CLI_OPTIONS_ALIAS_TO_NAME_MAP,
    CLI_OPTIONS_NAME_TO_ALIAS_MAP,
    CONFIG_KEY_NAME,
    CONFIG_KEY_ALIAS,
    INPUT_KEY_NAME,
    INPUT_KEY_ALIAS,
    OUTPUT_KEY_NAME,
    OUTPUT_KEY_ALIAS,
};