const ALPHABET = 'abcdefghijklmnopqrstuvwxyz'.split('');
const REVERSE_ALPHABET = ALPHABET.slice().reverse();
const DECODING_MODE = 'decoding';
const ENCODING_MODE = 'encoding';
const ENCRIPTION_DECODING_CODE = 0;
const ENCRIPTION_ENCODING_CODE = 1;
const ENCRIPTION_MODE_CODES_MAP = {
    [ENCRIPTION_DECODING_CODE]: DECODING_MODE,
    [ENCRIPTION_ENCODING_CODE]: ENCODING_MODE,
};
const STANDART_CAESAR_SHIFT_1 = 1;
const ROOT_8_SHIFT = 8;

module.exports = {
    ALPHABET,
    REVERSE_ALPHABET,
    DECODING_MODE,
    ENCODING_MODE,
    ENCRIPTION_MODE_CODES_MAP,
    ENCRIPTION_DECODING_CODE,
    ENCRIPTION_ENCODING_CODE,
    STANDART_CAESAR_SHIFT_1,
    ROOT_8_SHIFT,
};